# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('surname', models.CharField(default=None, max_length=300)),
                ('login', models.CharField(default=None, max_length=300)),
                ('password', models.CharField(default=None, max_length=300)),
                ('date_create', models.DateField(default=None)),
                ('date_bithday', models.DateField(default=None)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='finance.Account')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
    ]
