# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161117_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_create',
            field=models.DateField(default='2016-11-18'),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(default=None, max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
