#! /usr/bin/env python

import socket
from wsgiref.simple_server import make_server


def application(environ, start_response):

    response_body = [
        '%s: %s' % (key, value) for key, value in sorted(environ.items())
    ]
    response_body = '\n'.join(response_body)

    status = '200 OK'
    response_headers = [
        ('Content-Type', 'text/plain'),
        ('Content-Length', str(len(response_body)))
    ]
    start_response(status, response_headers)

    return [response_body]

hostname = socket.gethostname()
hostname_ip = socket.gethostbyname(hostname)
print hostname
print hostname_ip
httpd = make_server (
    'localhost',  # The host name
    8051, # A port number where to wait for the request
    application # The application object name, in this case a function
)

# Wait for a single request, serve it and quit
httpd.handle_request()